apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: simple-game-server
spec:
  replicas: 3
  template:
    spec:
      ports:
        - name: default
          containerPort: 7654
      template:
        # metadata:
        #   labels:
        #     app.kubernetes.io/instance-auto-gpt: bns
        #     app.kubernetes.io/part-of: 
        spec:
          containers:
            - name: simple-game-server
              image: us-docker.pkg.dev/agones-images/examples/simple-game-server:0.16
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "20m"
                limits:
                  memory: "64Mi"
                  cpu: "20m"
