name: Update README with Template Links

on:
  push:
    paths:
      - '.bunnyshell/templates/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures the entire git history is checked out


    - name: Generate Directory List and Update README
      run: |
        # Navigate to the templates directory
        cd .bunnyshell/templates

        # Generate the markdown links for each folder
        FOLDER_LINKS=$(find . -type d -mindepth 1 -exec bash -c 'echo "- [$(basename {})](https://github.com/aminalali8/bunnyshell-templates/tree/main/.bunnyshell/templates/$(basename {}))"' \;)

        # Print the folder links for debugging
        echo "Folder Links:"
        echo "$FOLDER_LINKS"

        # Navigate back to the root directory
        cd ../..

        # Prepare the new README section
        echo "## Template Directories" > temp_readme.md
        echo "$FOLDER_LINKS" >> temp_readme.md

        # Navigate back to the root directory
        cd ../..

        # Prepare the new README section
        echo "## Template Directories" > temp_readme.md
        echo "$FOLDER_LINKS" >> temp_readme.md
        
        # Replace the old README with the new file
        mv temp_readme.md README.md

        # Stage and commit the changes if there are any
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git config pull.rebase false
        git pull
        git add README.md
        git diff --staged --quiet || git commit -m "Update README with template links"
        git push
