name: Update README with Template Links

on:
  push:
    paths:
      - '.bunnyshell/templates/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Generate Directory List and Update README
        run: |       
          # Navigate to the GitHub workspace
          cd "$GITHUB_WORKSPACE"

          # Initialize an array to hold the GitHub links
          declare -a github_links

          # Iterate over each README.md file found
          while IFS= read -r file; do
            # Extract the folder name that comes after 'completed'
            folder=$(echo "$file" | sed -e "s|^completed/\([^/]*\)/.*|\1|")
            
            # Format the GitHub link
            github_link="- [$folder](https://github.com/aminalali8/bunnyshell-templates/tree/main/$file)"
            
            # Store the link in the array
            github_links+=("$github_link")
          done < <(find completed -type f -path '*/.bunnyshell/templates/*/README.md')

          # Prepare the new README section
          echo "## Completed Template Directories" > temp_readme.md
          for link in "${github_links[@]}"; do
            echo "$link" >> temp_readme.md
          done

          # Append the new section to the existing README.md
          cat README.md >> temp_readme.md

          # Replace the old README with the new file
          mv temp_readme.md README.md

          # Stage and commit the changes if there are any
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "Update README with template links"
          git push